version: "2.0"
services:
  service-1:
    image: 0xtiki/mai-thai-wallet:v0.0.2
    expose:
      - port: 3000
        as: 443
        to:
          - global: true
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - OPENAI_API_KEY
      - AKASH_API_KEY
      - NEXT_PUBLIC_WC_PROJECT_ID
      - CHAIN_ID
      - KV_REST_API_URL
      - >-
        KV_REST_API_TOKEN
      - ALCHEMY_API_KEY
      - BRIAN_API_KEY
      - MAITHAI_API_KEY
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        service-1:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 10000
      attributes:
        console/trials: "true"
      signedBy:
        anyOf: []
        allOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1