version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL
      - AKASH_API_KEY
      - NEXT_PUBLIC_WC_PROJECT_ID
      - CHAIN_ID
      - WALLET_ADDRESS
      - KV_REST_API_URL
      - KV_REST_API_TOKEN
      - ALCHEMY_API_KEY
      - BRIAN_API_KEY
      - MAITHAI_API_KEY
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next