import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProviders from '@/components/ClientProviders';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//style from CDP kit
import '@coinbase/onchainkit/styles.css';
import '@rainbow-me/rainbowkit/styles.css';
import { kv } from "@vercel/kv";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  await kv.del("transactions");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
